### PR TITLE
Update for OpenLDAP 2.4.49

### PR DESCRIPTION
**Pull request by quanah**
Updates Zimbra OpenLDAP build to work with the latest 2.4.49 release

### CODE REVIEW

**Comment by trantor** [comment]
Aren't the package changelogs/specs modifications ignoring/deleting references to previous iterations of the packages?

**Comment by quanah** [comment]
@trantor Yep, it's a new release.

**Comment by trantor** [comment]
Yep, that much I understood.
What I don't understand is why in the package changelog the latest version was
`zimbra-openldap (VERSION-1zimbra8.7b3ZAPPEND)` with `zimbra-openldap (VERSION-1zimbra8.7b1ZAPPEND)` released in 2018 and with your commit is now back to b1 from b3.
Am I missing something?
￼Cheers.

**Comment by quanah** [comment]
Yes.  The VERSION string will be replaced with 2.4.49 (current openldap version).  This is BUILD 1 of that new version (Thus VERSION-1zimbra8.7b1ZAPPEND).

The prior build was the 3rd build of 2.4.48 (Thus VERSION-1zimbra8.7b3ZAPPEND)

New version, new history.

**Comment by trantor** [comment]
Oh ok, now I understand. Thank you!

**Pull request merged**
