### PR TITLE
Allow out-of-tree builds by setting BUILD_ROOT

### PR DESCRIPTION
**Pull request by mss**
This changeset allows builds to be performed in a build dir which isn't located in the source tree. This has several advantages:

* VirtualBox Shared Folders which are used ba Vagrant break autoconf detection of mmap(2) and sendfile(2), resulting in weird effects (cf. eg. https://bugzilla.zimbra.com/show_bug.cgi?id=97278 and https://bugzilla.zimbra.com/show_bug.cgi?id=97256).
* Cleaning up the build results is only a simple quick `rm -rf $BUILD_ROOT` away.

If you specify `BUILD_ROOT` when executing `make` the Makefiles will recreate the same folder structure as in `THIRDPARTY_ROOT` there. To make this failsafe, it required a change which touched all `Makefile`s: `BUILD_DIR` (formerly known as `TMP_DIR`) has to point to an absolute path.

I did several full rebuilds of the whole tree to test this changeset.

My current script to use this looks like this (it depends on a few other changes which you can find in my branch [hack/make-world](https://github.com/mss/zimbra-packages/tree/hack/make-world), some of which will follow as separate pull requests once I cleaned them up):

```bash
#!/bin/bash
set -e -o pipefail

THE_BUILD_ROOT=/srv/zimbra-build
THE_REPO_ROOT=/srv/zimbra-repo
THE_THIRDPARTY_ROOT=$(dirname "$0")/../../zimbra-packages

sudo install -o $USER -d $THE_BUILD_ROOT

sudo ln -sf $THE_BUILD_ROOT/world/deb/build $THE_REPO_ROOT
sudo tee /etc/apt/sources.list.d/zimbra.list <<< "deb file:$THE_REPO_ROOT UBUNTU14_64/"

cd $THE_THIRDPARTY_ROOT
exec make BUILD_ROOT=$THE_BUILD_ROOT WGET=$PWD/../zimbra-cache/bin/cwget "$@"
```

### CODE REVIEW

**Comment by plobbes** [comment]
Lets add a comment about https://www.virtualbox.org/ticket/819 by the BUILD_ROOT definition (unless you think there's a better place).  Maybe it'll clue someone else in later about one of the issues it helps to address.

**Comment by mss** [comment]
I added a comment in b61d0f0

**Comment by plobbes** [comment]
+1

**Comment by mss** [comment]
I force-pushed a small fix (mistyped a hash sign as an asterisk, oops)

**Comment by quanah** [comment]
This is going to break my script for transferring packages, but I can fix that easily enough. ;)

+1

**Comment by mss** [comment]
My next patchset will include a hook to transfer packages so you'll be able to use just that :-)

**Comment by quanah** [comment]
Probably not. ;)

**Pull request merged**
