### PR TITLE
feature/nginx-throttling

### PR DESCRIPTION
**Pull request by gordyt**
### Summary

This pull request contains the following work that was done on the old `zms-dev` branch:

1. Rohan's work for [bug 106498](https://bugzilla.zimbra.com/show_bug.cgi?id=106498)
2. My work for the following tickets:
    * [ZMS-55](https://jira.corp.synacor.com/browse/ZMS-55)
    * [ZMS-59](https://jira.corp.synacor.com/browse/ZMS-59)

**Note:** The other ticket numbers mentioned in the commits refer to sub-tasks of the above.

### 2017-05-11 Updates

* Rebased onto `develop`.
* DEB/RPM changelog updates

### CODE REVIEW

**Comment by gordyt** [comment]
@rohan-ambasta Hey you may want to make a slight tweak to your change.  I'm seeing this:

    $ zmproxyctl start
    Starting proxy...nginx: [warn] The upstream_fair_shm_size is 0. The upstream_fair_shm_size value must be at least 32KiB
    done.

I don't know that it is necessary for the user to see that.  IIRC, your code will automatically set the size to the 32KiB value if necessary.

**Comment by rohan-ambasta** [comment]
@gordyt upstream_fair_shm_size is zero because it is not set in the nginx.conf.web.template file.
This error will go once upstream_fair_shm_size is added into the template by making code changes in ProxyConfGen.java

**Comment by gordyt** [comment]
Thank you for the update @rohan-ambasta. Is there a Jira ticket that covers the work of updating the template and `ProxyConfGen`?  Just want to make sure that is not overlooked.

**Comment by tmclane** [comment]
@gordyt @rohan-ambasta  Do you want me to address the "Is there a Jira ticket that covers the work of updating the template and ProxyConfGen?"

**Comment by rohan-ambasta** [comment]
@gordyt Since you are working on the change, you can go ahead and fix it. There is no JIRA ticket for this.

**Comment by tmclane** [comment]
@rohan-ambasta I'll make the ticket and issue a new PR to address the missing entry in the template and the ProxyConfGen.java

**Comment by tmclane** [comment]
Can we consider this closed in that case?

**Comment by gordyt** [comment]
merged and closed

**Pull request closed without merging**
