### PR TITLE
Add a .gitignore to ignore generated & symlinked stuff

### PR DESCRIPTION
**Pull request by mss**

### CODE REVIEW

**Comment by quanah** [comment]
There shouldn't be a zimbra-build directory inside of packages.

**Comment by mss** [comment]
But it is required, isn't it? I symlinked zimbra-build from that repo to make it work.

**Comment by quanah** [comment]
zimbra-build should be up one level, in its own checkout:
build@genesis:~/git/87$ ls -l
total 8
drwxrwxr-x 5 build build 4096 Mar  2 16:23 packages
drwxrwxr-x 5 build build 4096 Feb  3 14:23 zimbra-build

**Comment by mss** [comment]
Hm. I didn't really count the `..`s but just assumed that `SRC_ROOT` in
`BUILD_PLATFORM ?= $(shell sh $(SRC_ROOT)/zimbra-build/rpmconf/Build/get_plat_tag.sh)`
points to the `packages` top level. I'll update the pull request.

**Comment by mss** [comment]
Now only all `tmp` directories are ignored. (What do you think about changing `tmp` to `build` BTW?)

**Comment by quanah** [comment]
+1

**Comment by quanah** [comment]
Is there a compelling reason for it to be build over tmp?

**Comment by mss** [comment]
Just that it helps a bit navigating the tree on first sight, I was looking for the generated `deb`s a bit initially and thought the ones in `tmp` weren't the final ones since, well `tmp`. `build` is used in the Java source tree as well.

From the whole process of `apt-get`ing `zimbra-foo` packages it looks like there's missing a final step which pushes the `deb`s into some kind of local repo, so maybe `tmp` is adequate. *shrug*

**Comment by quanah** [comment]
It doesn't really matter to me either way. ;)  There is no step for adding the packages to a repository because configuring/defining that repository is up to the person who is building out the new platform.  We maintain both our deb & rpm repositories on the same server, using reprepro for the debs and createrepo for the RPMs.  We are also working with the Zeta Alliance on hosting repositories for unofficial operating systems.  There is quite a bit that goes into such a setup, including a GPG key for signing the RPMs and debs, etc.  This would allow a trusted source for unofficial OSes to exist.

**Comment by mss** [comment]
Right now just building the packages tree without any existing infrastructure is a bit tedious.

I created some hack to be able to just say `make world` on the top level with a local `dpkg-scanpackages` based repo (cf. https://github.com/Zimbra/packages/compare/master...mss:hack/make-world). I'll clean up some parts of that and create a separate pull request which optionally allows one to use such a local repo.

**Pull request merged**
