### PR TITLE
Update for OpenLDAP 2.4.56

### PR DESCRIPTION
**Pull request by quanah**
It is critical that Zimbra updates to the OpenLDAP 2.4.56 release as numerous fixes to multi-master replication have been made since the 2.4.49 release.

### CODE REVIEW

**Comment by Prashantsurana** [comment]
Thanks @quanah  , much appreciated. 

@umagmrit  can you please target for next release.

**Comment by ghen2** [comment]
Better look at OpenLDAP 2.5.x by now?  It contains most if not all patches @quanah backported to 2.4 over the years?

**Review by RBDurgin — APPROVED** [review]

**Comment by quanah** [comment]
> 
> 
> Better look at OpenLDAP 2.5.x by now? It contains most if not all patches @quanah backported to 2.4 over the years?

Yes, not only does it include all the backported bits, it includes other functionality that would help significantly, such as the ability to store the syncprov sessionlog in the accesslog DB.

**Comment by Prashantsurana** [comment]
Thanks @quanah , can you please submit the pull request for 2.5.x ? 
Let us know, if there is any specific upgrade step required.

**Comment by quanah** [comment]
> Thanks @quanah , can you please submit the pull request for 2.5.x ?

No, I cannot.  This is not a trivial bit of work and Synacor needs to decide how it wants to proceed for 2.5

> Let us know, if there is any specific upgrade step required.

The OpenLDAP 2.5 admin guide has a section on upgrading that lists what's necessary.

**Comment by Prashantsurana** [comment]
Thanks @quanah will reach out from  2.5.x upgrade, 
can you please submit  pull request for 2.4.57  ?  We have seen some significant issues being fixed here.

**Comment by Prashantsurana** [comment]
@quanah  This gives compilation error.

```
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd openldap-2.4.56
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #0 (ITS5037.patch):'
Patch #0 (ITS5037.patch):
+ /bin/cat /home/build/git/88/packages/thirdparty/openldap/build/RHEL6_64/zimbra-openldap/rpm/SOURCES/ITS5037.patch
+ /usr/bin/patch -p1 --fuzz=0
patching file servers/slapd/back-bdb/filterindex.c
Hunk #1 succeeded at 741 (offset 101 lines).
Hunk #2 succeeded at 858 (offset 102 lines).
Hunk #3 succeeded at 978 (offset 103 lines).
Hunk #4 succeeded at 1095 (offset 104 lines).
patching file servers/slapd/back-mdb/filterindex.c
Hunk #1 succeeded at 734 (offset 29 lines).
Hunk #2 succeeded at 850 (offset 29 lines).
Hunk #3 succeeded at 969 (offset 29 lines).
Hunk #4 succeeded at 1085 (offset 29 lines).
+ echo 'Patch #1 (writers.patch):'
Patch #1 (writers.patch):
+ /bin/cat /home/build/git/88/packages/thirdparty/openldap/build/RHEL6_64/zimbra-openldap/rpm/SOURCES/writers.patch
+ /usr/bin/patch -p1 --fuzz=0
patching file servers/slapd/connection.c
Hunk #5 succeeded at 778 (offset 20 lines).
Hunk #6 succeeded at 1306 (offset 20 lines).
Hunk #7 succeeded at 1930 (offset 20 lines).
Hunk #8 succeeded at 1957 (offset 20 lines).
patching file servers/slapd/daemon.c
Hunk #3 succeeded at 1011 (offset 45 lines).
Hunk #4 succeeded at 1050 (offset 45 lines).
Hunk #5 succeeded at 1062 (offset 46 lines).
Hunk #6 succeeded at 2416 (offset 65 lines).
Hunk #7 succeeded at 2499 (offset 65 lines).
Hunk #8 succeeded at 3132 (offset 68 lines).
patching file servers/slapd/proto-slap.h
patching file servers/slapd/result.c
+ echo 'Patch #2 (ITS7683.patch):'
Patch #2 (ITS7683.patch):
+ /bin/cat /home/build/git/88/packages/thirdparty/openldap/build/RHEL6_64/zimbra-openldap/rpm/SOURCES/ITS7683.patch
+ /usr/bin/patch -p1 --fuzz=0
patching file libraries/libldap/tls2.c
Hunk #1 succeeded at 705 (offset 30 lines).
Hunk #2 succeeded at 1044 (offset 32 lines).
patching file libraries/libldap/tls_o.c
Hunk #1 succeeded at 846 (offset 170 lines).
Hunk #2 succeeded at 1377 (offset 80 lines).
patching file libraries/libldap/ldap-tls.h
patching file libraries/libldap/tls_g.c
Hunk #1 succeeded at 669 (offset 4 lines).
Hunk #2 succeeded at 939 (offset 4 lines).
patching file doc/man/man3/ldap_get_option.3
Hunk #1 succeeded at 628 (offset 20 lines).
Hunk #2 succeeded at 803 (offset 43 lines).
patching file include/ldap.h
Hunk #1 FAILED at 158.
1 out of 1 hunk FAILED -- saving rejects to file include/ldap.h.rej
patching file include/ldap_pvt.h
Hunk #1 succeeded at 421 (offset 1 line).
patching file servers/slapd/connection.c
Hunk #1 succeeded at 1378 (offset -8 lines).
Hunk #2 succeeded at 1396 (offset -8 lines).
error: Bad exit status from /var/tmp/rpm-tmp.dmm50j (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.dmm50j (%prep)
make: *** [build_rpm] Error 1

```

**Comment by Prashantsurana** [comment]
https://github.com/Zimbra/packages/pull/130 

Kindly review the fixes.

**Comment by ghen2** [comment]
FWIW I already provided this as part of https://github.com/Zimbra/packages/pull/117. ;-)

**Comment by Prashantsurana** [comment]
https://controlc.com/a7d769ee

**Comment by Prashantsurana** [comment]
Thanks @ghen2 can you please rebase submit pull request against **feature/openldap-2.4.56** for pw-argon2

**Comment by ghen2** [comment]
Done, it has a minimal diff against feature/openldap-2.4.56 now.

**Comment by ghen2** [comment]
@Prashantsurana, can you still consider https://github.com/Zimbra/packages/pull/117 please?
It now only updates libsodium and adds the pw-argon2 module to openldap.

**Comment by ghen2** [comment]
Hi

As OpenLDAP 2.4 is EOL and [OpenLDAP 2.5 is now an LTS release](https://lists.openldap.org/hyperkitty/list/openldap-announce@openldap.org/thread/2QQNVWPUUG54JM7FGQHMMF3H4KS2PPKQ/), Zimbra should consider moving to OpenLDAP 2.5 now.  It contains all of the [patches here](https://github.com/Zimbra/packages/tree/develop/thirdparty/openldap/patches) so will be much easier to maintain.

Upgrading requires a one-time slapcat/slapadd of the database though, not sure how you'd handle this in a patch release.  I'd certainly ship it in a beta repo first, like you did for TLS 1.3, for customers to test.

Replication works between 2.4 and 2.5, so you can upgrade one LDAP server at a time.

**Comment by quanah** [comment]
>
> Upgrading requires a one-time slapcat/slapadd of the database though, not sure how you'd handle this in a patch release. 

This statement is incorrect.  There is no need to export or import the database going from 2.4 to 2.5.  It should be a straight drop-in upgrade.

Regards,
Quanah

**Comment by ghen2** [comment]
Hi @Prashantsurana 

What's Zimbra's roadmap wrt upgrading OpenLDAP to a supported release again?

**Comment by umagmrit** [comment]
@uttamtakalkar @silentsakky @dawoodshaikh FYI

**Pull request merged**
