### PR TITLE
Fixed typo in usage of zmauth_type, ported ngx_http_zm_sso_module to …

### PR DESCRIPTION
**Pull request by ZeXtrasJay**
Fixed typo in usage of zmauth_type, ported ngx_http_zm_sso_module to zmauth_type

### CODE REVIEW

**Comment by thefoolwhocodes** [comment]
I would be keen to know the same as mentioned by @gordyt .

**Comment by ZeXtrasJay** [comment]
@gordyt 
> May I ask what testing you have done with this change?
Only checked compilation

**Comment by ZeXtrasJay** [comment]
@thefoolwhocodes 
Is there some blocker here?

**Comment by thefoolwhocodes** [comment]
I feel we could write some testing details here @ZeXtrasJay.

**Comment by ZeXtrasJay** [comment]
@thefoolwhocodes 
I will test on a multiserver environment checking that all requests are correctly redirected to the correct mailboxd on both drive & zwc.
If I do it today, can you merge for this patch for the upcoming patch cycle?

**Comment by thefoolwhocodes** [comment]
@AMSrivastava please update the merge plan for this.

**Comment by thefoolwhocodes** [comment]
@ZeXtrasJay any update on this regarding testing.

**Comment by ZeXtrasJay** [comment]
I've finished the validation:
cluster: 2 mbox, 1 ldap, 1 proxy

1. drive configuration plus this patch on proxy
2. mbox with patched lookup handler & drive
3. setup drive zimlet
4. create a group of users with zimbraMailHost for both mbox1 and mbox2 
5. changed logging verbosity: log4j.logger.zimbra.nginxlookup=DEBUG in each mbox
6. zxsuite --host all_servers core setProperty ZxCore_LogLevel debug
7. logged in with users for both mailboxes passing thorugh proxy server
8. checks drive is correctly redirected by checking requests logs in mailbox.log
9. validated accounts by checking nginx-lookup in mailbox.log:
> 2019-01-21 15:19:31,547 DEBUG [qtp1286783232-849:https:https://172.18.0.6/service/extension/nginx-lookup] [] nginxlookup - SendingResult mailhost=172.18.0.5 port=8743 clientIp=172.18.0.1

The presence of port 8743 means the patch is fully working and Auth-Zimbra-Zx is passed correctly.

No anomalies has been found in nginx logs.

**Comment by thefoolwhocodes** [comment]
Thanks @ZeXtrasJay for the update.

**Comment by srivastava-ami** [comment]
This PR is been merged with the mentioned branch and the created package from that is been updated in the dev repo, Which is available to the testing to QA.

**Comment by thefoolwhocodes** [comment]
Thanks @srivastava-ami

**Pull request merged**
