### PR TITLE
Feature/zcs 8956 - Upgrade Nginx -> 1.17.9

### PR DESCRIPTION
**Pull request by tmclane**
This branch upgrades Nginx to 1.17.9.

At this point it compiles and builds packages - I have not tested them yet.

The **README** for the _thirdparty/nginx_ was updated to describe how I would like further improvements to the patched Nginx to proceed from this point onwards.

The patch itself is created by making changes in the github.com/Zimbra/nginx repository and then using `git diff <base commit/release tag> > file.patch`.

The `configure` file and any other files that are `created` but already exist in the target directory will cause user intervention and must be removed from the patch file.  Please remove that from any patch before committing.  I am currently testing this work at this time.

### CODE REVIEW

**Comment by tmclane** [comment]
For some reason the built Nginx is triggering a sudo request when restarting.

```
	Starting proxy...[sudo] password for zimbra:
```

Looking into this issue at this time.

**Comment by Prashantsurana** [comment]
is docker as build image is hard requirement?  or can this build in current vagrant images we have? 
If you do not know please check with @umagmrit . Zimbra 8/9 we have to ship for Ubuntu14 , Ubuntu16, Ubuntu18, RHEL6,RHEL7 and RHEL8  
We have already infrastructure in place to build the packages for all OS. 

If docker ease up the development, it is nice but I want to make sure we should able to build on existing env.

**Comment by geert-hendrickx-be** [comment]
Will this be released for Zimbra 8.8.15 as well, or just Zimbra 9+?  Newer nginx contains many relevant features for existing production deployments, including HTTP/2, ability to deploy RSA and ECDSA certificates in parallel, etc.  Users interested in those features can enable them in the nginx config templates directly, without the need for full zmprov config integration, at least initially.

**Comment by tmclane** [comment]
@prash

> is docker as build image is hard requirement? or can this build in current vagrant images we have?
> If you do not know please check with @umagmrit . Zimbra 8/9 we have to ship for Ubuntu14 , Ubuntu16, Ubuntu18, RHEL6,RHEL7 and RHEL8
> We have already infrastructure in place to build the packages for all OS.
> 
> If docker ease up the development, it is nice but I want to make sure we should able to build on existing env.

Docker is not a hard requirement.  I added it to ease development only.  The docker image is merely to provide a consistent development environment for the developer. 

It's much easier to spin up a Docker container than it is to build a workable VM to build packages.

**Comment by geert-hendrickx-be** [comment]
To build on CentOS/RedHat, I had to apply the same changes to the RPM spec as to debian/rules:

```
--- a/thirdparty/nginx/zimbra-nginx/rpm/SPECS/nginx.spec
+++ b/thirdparty/nginx/zimbra-nginx/rpm/SPECS/nginx.spec
@@ -60,3 +60,2 @@ CFLAGS="-g -O0"; export CFLAGS; \
   --with-debug \
-  --with-ipv6 \
   --with-http_ssl_module \
@@ -64,7 +63,3 @@ CFLAGS="-g -O0"; export CFLAGS; \
   --with-pcre \
-  --with-http_upstream_zmauth_module \
-  --with-http_zm_sso_module \
-  --with-http_spdy_module \
   --with-mail \
-  --with-mail-sasl \
   --with-mail_ssl_module \
@@ -77,2 +72,9 @@ CFLAGS="-g -O0"; export CFLAGS; \
   --without-http_uwsgi_module \
+  --with-http_v2_module \
+  --with-mail-sasl \
+  --with-ipv6 \
+  --with-http_upstream_zmauth_module \
+  --with-http_zm_sso_module \
+  --with-mail_throttle \
+  --with-mail_zmauth \
   --add-module=modules/nviennot-nginx-tcp-keepalive
``` 
However, it seems the Zimbra modules (zmauth etc) are not actually built.  Running it in a Zimbra environment throws various errors for unknown config directives.

**Comment by tmclane** [comment]
> To build on CentOS/RedHat, I had to apply the same changes to the RPM spec as to debian/rules:
> 
> ```
> --- a/thirdparty/nginx/zimbra-nginx/rpm/SPECS/nginx.spec
> +++ b/thirdparty/nginx/zimbra-nginx/rpm/SPECS/nginx.spec
> @@ -60,3 +60,2 @@ CFLAGS="-g -O0"; export CFLAGS; \
>    --with-debug \
> -  --with-ipv6 \
>    --with-http_ssl_module \
> @@ -64,7 +63,3 @@ CFLAGS="-g -O0"; export CFLAGS; \
>    --with-pcre \
> -  --with-http_upstream_zmauth_module \
> -  --with-http_zm_sso_module \
> -  --with-http_spdy_module \
>    --with-mail \
> -  --with-mail-sasl \
>    --with-mail_ssl_module \
> @@ -77,2 +72,9 @@ CFLAGS="-g -O0"; export CFLAGS; \
>    --without-http_uwsgi_module \
> +  --with-http_v2_module \
> +  --with-mail-sasl \
> +  --with-ipv6 \
> +  --with-http_upstream_zmauth_module \
> +  --with-http_zm_sso_module \
> +  --with-mail_throttle \
> +  --with-mail_zmauth \
>    --add-module=modules/nviennot-nginx-tcp-keepalive
> ```
> 
> However, it seems the Zimbra modules (zmauth etc) are not actually built. Running it in a Zimbra environment throws various errors for unknown config directives.

FYI: This is not ready for prime time.   Please don't expect it to run yet.   I should have opened this as a draft PR.

**Comment by tmclane** [comment]
Thanks for reminding me I need to make the same changes to the RPM file though!

**Comment by geert-hendrickx-be** [comment]
./configure: warning: the "--with-ipv6" option is deprecated

**Comment by tmclane** [comment]
> ./configure: warning: the "--with-ipv6" option is deprecated

Thanks for looking.  It's still not ready :).

**Comment by geert-hendrickx-be** [comment]
This build now works in our non-production environment.  Including new nginx features HTTP/2.0 and combined RSA+ECDSA certificates.

**Comment by geert-hendrickx-be** [comment]
What's the status of this pull request please?  It is working in our tests, and we'd like to deploy this in production.
Is there anything left to do before this can be merged?

**Comment by thefoolwhocodes** [comment]
@geert-hendrickx-be the work in in WIP, we will updating once done. Thanks.

**Comment by thefoolwhocodes** [comment]
Closing the PR as this work has already been taken care of following a different approach.

**Pull request closed without merging**
