### PR TITLE
Update openjdk-cacerts from Mozilla NSS 3.92

### PR DESCRIPTION
**Pull request by ghen2**

### CODE REVIEW

**Comment by ghen2** [comment]
This will have to be tested for ZBUG-2400 again.

**Comment by ghost** [comment]
@ghen2 can you please describe the steps you took to obtain the contents of certdata.txt? Thanks!

**Comment by ghen2** [comment]
wget https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt

**Comment by ghen2** [comment]
or https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt for the latest NSS release, instead of the master branch.

**Comment by ghen2** [comment]
Ideally the CA trust store should be updated regularly; yearly or even quarterly, see https://wiki.mozilla.org/NSS:Release_Versions.

**Comment by ghost** [comment]
Looking at commit history, we have been including https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt in the past.

References:
https://mail.openjdk.org/pipermail/jdk-dev/2020-May/004311.html
https://github.com/adoptium/adoptium-support/issues/13#issuecomment-626147267

**Comment by ghost** [comment]
@umagmrit  What would you think about changing the  https://github.com/Zimbra/packages/blob/develop/thirdparty/openjdk-cacerts/Makefile to wget the latest version at build time?

**Comment by ghen2** [comment]
FWIW Mozilla nowadays advises against parsing certdata.txt directly, as it contains metadata that may not be interpreted correctly, as well as CA certificates not intended for TLS: https://blog.mozilla.org/security/2021/05/10/beware-of-applications-misusing-root-stores/

If you're going to change the mechanism anyway, maybe better download the root certificates in PEM format directly from [CCADB](https://www.ccadb.org/resources) and import with java keytool.

Or use curl's [mk-ca-bundle](https://curl.se/docs/mk-ca-bundle.html) to reliably parse certdata.txt and generate a PEM bundle to import with java keytool (this is suggested in your second link to adoptium).

**Comment by umagmrit** [comment]
> @umagmrit What would you think about changing the https://github.com/Zimbra/packages/blob/develop/thirdparty/openjdk-cacerts/Makefile to wget the latest version at build time?

yes we can use wget to get the latest version

**Comment by ghost** [comment]
Adding ZCS-13930: Instead of manually fetching the cacerts, adding it to the repo and then build Zimbra....
Please change https://github.com/Zimbra/packages/blob/develop/thirdparty/openjdk-cacerts/Makefile so that the latest version of cacerts is fetched each time Zimbra is build.

**Comment by umagmrit** [comment]
This has been taken care of by https://github.com/Zimbra/packages/pull/195

**Pull request closed without merging**
